language: php

php:
  - 5.4
  - 5.5

before_install:
 - wget "https://packages.zendframework.com/releases/ZendFramework-2.1.5/ZendFramework-minimal-2.1.5.tgz"
 - tar -zxf ZendFramework-minimal-2.1.5.tgz
 - mkdir -p Libraries/zendframework
 - mv ZendFramework-minimal-2.1.5 Libraries/zendframework/zendframework
 - wget "https://github.com/zendframework/ZendOAuth/archive/release-2.0.1.zip"
 - unzip release-2.0.1.zip -d Libraries/zendframework/
 - mv Libraries/zendframework/ZendOAuth-release-2.0.1 Libraries/zendframework/zendoauth
 - mkdir -p Libraries/ruflin
 - wget "https://github.com/ruflin/Elastica/archive/v0.20.5.0.RC1.zip"
 - unzip v0.20.5.0.RC1.zip -d Libraries/ruflin/
 - mv Libraries/ruflin/Elastica-0.20.5.0.RC1 Libraries/ruflin/elastica
 - mysql -e 'create database rbschangetest;'
 - bash ChangeTests/travisconfig/init.sh

script:
 - cd ChangeTests/
 - phpunit --configuration phpunit.xml.dist
 - phpunit --configuration phpunit.xml.sqlite.dist

notifications:
   email:
       - noreply@rbschange.fr
