language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
 - curl -s https://getcomposer.org/installer | php -- --quiet
 - php composer.phar install --dev --no-interaction 
 - mysql -e 'create database rbschangetest;'
 - bash ChangeTests/travisconfig/init.sh

script:
 - cd ChangeTests/
 - phpunit --configuration phpunit.xml.dist
 - phpunit --configuration phpunit.xml.sqlite.dist

notifications:
   email:
       - noreply@rbschange.fr
