language: php

php:
  - 5.3
  - 5.4

before_install:
 - cp tests/TestConfiguration.php.travis tests/TestConfiguration.php
 - curl -s https://getcomposer.org/installer | php -- --quiet


script:
 - cd ChangeTests/
 - phpunit Change/
