language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
 - wget "https://packages.zendframework.com/releases/ZendFramework-2.1.1/ZendFramework-minimal-2.1.1.tgz"
 - tar -zxf ZendFramework-minimal-2.1.1.tgz
 - mkdir -p Libraries/zendframework
 - mv ZendFramework-minimal-2.1.1 Libraries/zendframework/zendframework
 - mysql -e 'create database rbschangetest;'
 - bash ChangeTests/travisconfig/init.sh

script:
 - cd ChangeTests/
 - phpunit --configuration phpunit.xml.dist
 - phpunit --configuration phpunit.xml.sqlite.dist

notifications:
   email:
       - noreply@rbschange.fr
