language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
 - wget "https://packages.zendframework.com/releases/ZendFramework-2.1.4/ZendFramework-minimal-2.1.4.tgz"
 - tar -zxf ZendFramework-minimal-2.1.4.tgz
 - mkdir -p Libraries/zendframework
 - mv ZendFramework-minimal-2.1.1 Libraries/zendframework/zendframework
 - wget "http://packages.zendframework.com/composer/ZendOAuth-2.0.1.zip"
 - unzip ZendOAuth-2.0.1.zip -d Libraries/zendframework/zendoauth
 - mysql -e 'create database rbschangetest;'
 - bash ChangeTests/travisconfig/init.sh

script:
 - cd ChangeTests/
 - phpunit --configuration phpunit.xml.dist
 - phpunit --configuration phpunit.xml.sqlite.dist

notifications:
   email:
       - noreply@rbschange.fr
