language: php

services:
  - elasticsearch

php:
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
 - composer selfupdate
 - composer install
 - mysql -e 'create database rbschangetest;'
 - bash ChangeTests/travisconfig/init.sh

script:
 - cd ChangeTests/
 - phpunit --configuration phpunit.xml.dist
 - phpunit --configuration phpunit.xml.sqlite.dist
 - phpunit --configuration phpunit.xml.plugins.dist
 - phpunit --configuration phpunit.xml.perf.dist

notifications:
   email:
       - noreply@rbschange.fr
